version: '3.8'

networks:
  app-net:
    driver: bridge

volumes:
  mariadb-data:

services:

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    container_name: keycloak_ezboot
    command:
      - start-dev
      - --import-realm                     # ⚠️ Retire cette ligne après premier import
      - --hostname-strict=false
    environment:
      KC_DB: mariadb
      KC_DB_URL_HOST: mariadb
      KC_DB_USERNAME: ${MARIADB_USER}
      KC_DB_PASSWORD: ${MARIADB_PASSWORD}
      KC_DB_URL_DATABASE: ${MARIADB_DATABASE}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - "8080:8080"
    volumes:
      - ./dockerfile/keycloak/import:/opt/keycloak/data/import:ro
    depends_on:
      - mariadb
    networks:
      - app-net

  mariadb:
    image: mariadb:lts
    container_name: mariadb_ezboot
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MARIADB_DATABASE}
      MYSQL_USER: ${MARIADB_USER}
      MYSQL_PASSWORD: ${MARIADB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - app-net

  app:
    build: ./backend/
    container_name: app_ezboot
    volumes: 
      - ./secrets:/run/secrets:ro
    restart: always
    depends_on:
      - mariadb
    ports:
      - "3000:3000"
    networks:
      - app-net
    platform: linux/amd64

  nginx:
    build: ./dockerfile/nginx/
    container_name: nginx_ezboot
    depends_on:
      - app
    ports:
      - "80:80"
    networks:
      - app-net
    restart: unless-stopped
