version: '3.8'

networks:
  app-net:
    driver: bridge

volumes:
  mariadb-data:

services:

  mariadb:
    image: mariadb:lts
    container_name: mariadb_ezboot
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MARIADB_DATABASE}
      MYSQL_USER: ${MARIADB_USER}
      MYSQL_PASSWORD: ${MARIADB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - app-net

  app:
    build: ./backend/
    container_name: app_ezboot
    volumes: 
      - ./secrets:/run/secrets:ro
    restart: always
    depends_on:
      - mariadb
    ports:
      - "3000:3000"
    networks:
      - app-net
    platform: linux/amd64

  nginx:
    build: ./dockerfile/nginx/
    container_name: nginx_ezboot
    depends_on:
      - app
    ports:
      - "80:80"
    networks:
      - app-net
    restart: unless-stopped
